// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// hudson_fst
double hudson_fst(NumericMatrix X1, NumericMatrix X2);
RcppExport SEXP _QGenTools_hudson_fst(SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(hudson_fst(X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// ibs
NumericMatrix ibs(NumericMatrix X);
RcppExport SEXP _QGenTools_ibs(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(ibs(X));
    return rcpp_result_gen;
END_RCPP
}
// r2
DataFrame r2(NumericMatrix X);
RcppExport SEXP _QGenTools_r2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(r2(X));
    return rcpp_result_gen;
END_RCPP
}
// r2s
DataFrame r2s(NumericMatrix X, NumericMatrix st);
RcppExport SEXP _QGenTools_r2s(SEXP XSEXP, SEXP stSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type st(stSEXP);
    rcpp_result_gen = Rcpp::wrap(r2s(X, st));
    return rcpp_result_gen;
END_RCPP
}
// r2v
DataFrame r2v(NumericMatrix X, NumericMatrix V);
RcppExport SEXP _QGenTools_r2v(SEXP XSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(r2v(X, V));
    return rcpp_result_gen;
END_RCPP
}
// r2vs
DataFrame r2vs(NumericMatrix X, NumericMatrix V, NumericMatrix st);
RcppExport SEXP _QGenTools_r2vs(SEXP XSEXP, SEXP VSEXP, SEXP stSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type st(stSEXP);
    rcpp_result_gen = Rcpp::wrap(r2vs(X, V, st));
    return rcpp_result_gen;
END_RCPP
}
// realized_ab
NumericMatrix realized_ab(NumericMatrix X);
RcppExport SEXP _QGenTools_realized_ab(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(realized_ab(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_QGenTools_hudson_fst", (DL_FUNC) &_QGenTools_hudson_fst, 2},
    {"_QGenTools_ibs", (DL_FUNC) &_QGenTools_ibs, 1},
    {"_QGenTools_r2", (DL_FUNC) &_QGenTools_r2, 1},
    {"_QGenTools_r2s", (DL_FUNC) &_QGenTools_r2s, 2},
    {"_QGenTools_r2v", (DL_FUNC) &_QGenTools_r2v, 2},
    {"_QGenTools_r2vs", (DL_FUNC) &_QGenTools_r2vs, 3},
    {"_QGenTools_realized_ab", (DL_FUNC) &_QGenTools_realized_ab, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_QGenTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
