# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
hudson_fst <- function(X1, X2) {
    .Call(`_QGenTools_hudson_fst`, X1, X2)
}

#' @export
ibs <- function(X) {
    .Call(`_QGenTools_ibs`, X)
}

#' @export
r2 <- function(X) {
    .Call(`_QGenTools_r2`, X)
}

#' @export
r2s <- function(X, st) {
    .Call(`_QGenTools_r2s`, X, st)
}

#' @export
r2v <- function(X, V) {
    .Call(`_QGenTools_r2v`, X, V)
}

#' @export
r2vs <- function(X, V, st) {
    .Call(`_QGenTools_r2vs`, X, V, st)
}

#' @export
realized_ab <- function(X) {
    .Call(`_QGenTools_realized_ab`, X)
}

